/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2c303d",
        "surface-bright": "#353946",
        "on-secondary-fixed": "#1e055a",
        "on-secondary-fixed-variant": "#4a3a87",
        "error-container": "#93000a",
        "on-secondary": "#33226f",
        "primary-fixed-dim": "#e6c364",
        "tertiary-fixed": "#dde1ff",
        "surface-variant": "#313442",
        "primary-fixed": "#ffe08f",
        "on-tertiary-container": "#2e3b77",
        "tertiary-fixed-dim": "#b9c3ff",
        "on-primary-container": "#503d00",
        "on-primary-fixed-variant": "#584400",
        "surface-container-high": "#262a37",
        "surface-container-highest": "#313442",
        "outline": "#99907e",
        "on-background": "#dfe2f3",
        "surface-container-lowest": "#0a0e1a",
        "surface-container": "#1b1f2c",
        "on-tertiary": "#1e2b66",
        "secondary-fixed-dim": "#cbbeff",
        "secondary": "#cbbeff",
        "on-secondary-container": "#baa9ff",
        "inverse-surface": "#dfe2f3",
        "primary-container": "#c9a84c",
        "on-error": "#690005",
        "background": "#0f131f",
        "on-primary": "#3d2e00",
        "surface": "#0f131f",
        "tertiary": "#b9c4ff",
        "tertiary-container": "#9ba8eb",
        "secondary-container": "#4a3a87",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#e7deff",
        "on-tertiary-fixed-variant": "#35437e",
        "on-surface-variant": "#d0c5b2",
        "surface-container-low": "#171b28",
        "on-surface": "#dfe2f3",
        "primary": "#e6c364",
        "surface-dim": "#0f131f",
        "inverse-primary": "#755b00",
        "surface-tint": "#e6c364",
        "on-primary-fixed": "#241a00",
        "on-tertiary-fixed": "#041451",
        "error": "#ffb4ab",
        "outline-variant": "#4d4637",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
    },
  },
  plugins: [],
}
